markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
show_drafts: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: "\n\n"
timezone: Europe/Rome
exclude: ["Gemfile", "Gemfile.lock", "README.md", "bin"]
github:
  username: mailwatch/mailwatch.github.io
google_analytics_id: UA-xxxx-xx
